---
title: Modelling global trends in COVID-19 cases
author: Caleb Moses
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
    prettydoc::html_pretty:
      theme: tactile
highlight: github
---

```{r import-libraries, message = FALSE, echo = FALSE}

# Import libraries
library(tidyverse)
library(nCov2019)
library(wbstats)
library(broom)
library(furrr)
library(rstan)
library(brms)
library(here)

# Use furr multiprocessing
plan(multiprocess)

# Set default ggplot theme
theme_set(theme_minimal() + theme(plot.title = element_text(hjust = 0.5)))

# Set up stan options
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

knitr::opts_chunk$set(echo = FALSE, fig.align = "center", warning = FALSE, message = FALSE, fig.width = 12)

```

## Get the data

We fetch the latest covid-19 data using the `nCov2019` R package.

```{r get-data}

calculate_new_cases <- function(x) {
    lag_x <- lag(x)
    last_x <- ifelse(is.na(lag_x), 0, lag_x)
    x - last_x
}

# Get global COVID-19 data
covid_data <- load_nCov2019(lang = 'en')['global'] %>%
    filter(!is.na(country)) %>%
    group_by(time, country) %>%
    summarise_at(vars(cum_confirm:cum_dead), sum) %>%
    ungroup() %>%
    group_by(country) %>%
    mutate(new_confirm = calculate_new_cases(cum_confirm),
           new_heal = calculate_new_cases(cum_heal),
           new_dead = calculate_new_cases(cum_dead)) %>%
    ungroup()

covid_data %>%
    select(time, country, starts_with("new")) %>%
    gather(starts_with("new"), key = 'variable', value = 'cases') %>%
    ggplot(aes(x = time, y = cases, colour = variable)) +
    geom_point() +
    scale_y_log10() +
    facet_wrap(~country)

covid_data %>%
    ggplot(aes(x = time, y = new_confirm, colour = country)) +
    geom_point() +
    scale_y_log10() +
    facet_wrap(~country) +
    guides(colour = FALSE)

covid_data %>%
    ggplot(aes(x = time, y = new_dead, colour = country)) +
    geom_point() +
    scale_y_log10() +
    facet_wrap(~country) +
    guides(colour = FALSE)


covid_data

# Get global population data
pop_data <- wb(indicator = "SP.POP.TOTL", startdate = 1900, enddate = 2019) %>%
    mutate_at(c("date", "value"), as.integer) %>%
    mutate(country = case_when(
               country == "Russian Federation" ~ "Russia",
               country == "Iran, Islamic Rep." ~ "Iran",
               country == "Korea, Dem. People’s Rep." ~ "South Korea",
               country == "Egypt, Arab Rep." ~ "Egypt",
               country == "Brunei Darussalam" ~ "Brunei",
               country == "Venezuela, RB" ~ "Venezuela",
               country == "Bahamas, The" ~ "Bahamas",
               country == "Gambia, The" ~ "Gambia",
               TRUE ~ country)) %>%
    select(-indicator, -indicatorID) %>%
    filter(country %in% covid_data$country) %>%
    arrange(country, date)

```

## Visualise the data

Here we plot the number of confirmed cases over time.

```{r cases-over-time}

# Plot the number of cases over time
covid_data %>%
    ggplot(aes(x = time, y = cum_confirm, colour = country)) +
    geom_point() +
    geom_line() +
    facet_wrap(~country) +
    guides(colour = FALSE) +
    ylab("Cumulative confirmed cases") +
    ggtitle("Number of COVID-19 cases internationally by country")

# Plot the number of cases over time
covid_data %>%
    ggplot(aes(x = time, y = cum_confirm, colour = country)) +
    geom_point() +
    geom_line() +
    facet_wrap(~country) +
    scale_y_log10() +
    guides(colour = FALSE) +
    ylab("Cumulative confirmed cases") +
    ggtitle("Number of COVID-19 cases internationally by country (log scale)")

```

## Model the data

We are going to model a single country first (Italy), then we'll try to extend the model
to all of the countries.

```{r}

selected_country <- "New Zealand"

country_pop <- pop_data %>%
    filter(country == selected_country) %>%
    filter(date == max(date)) %>%
    .$value

country_data <- covid_data %>%
    filter(country == selected_country)

# Prior simulation
country_prior_fit <- stan(
    file = here("analysis/country_prior.stan"),
    data = list(
        N = nrow(country_data),
        y = country_data$new_confirm,
        P = country_pop),
    iter = 2000,
    chains = 4,
    algorithm = "Fixed_param"
)

extract(country_prior_fit) %>%
    .$y_prior %>%
    as_tibble() %>%
    add_column(sim = 1:nrow(.), .before = "V1") %>%
    gather(paste0("V", 1:(ncol(.)-1)), key = 'timestep', value = 'y') %>%
    mutate(timestep = as.integer(str_remove(timestep, "V"))) %>%
    ggplot(aes(x = timestep, y = y, group = sim)) +
    geom_line(alpha = 0.1) +
    scale_y_log10()

```

```{r}

# Prior simulation
country_post_fit <- stan(
    file = here("analysis/country_model.stan"),
    data = list(
        N = nrow(country_data),
        y = country_data$new_confirm,
        P = country_pop,
        T = 5),
    iter = 2000,
    chains = 4
)

country_post_fit

extract(country_post_fit) %>%
    .$y %>%
    as_tibble() %>%
    add_column(sim = 1:nrow(.), .before = "V1") %>%
    gather(paste0("V", 1:(ncol(.)-1)), key = 'time', value = 'new_confirm') %>%
    mutate(time = as.integer(str_remove(time, "V")) + min(country_data$time) - 1) %>%
    group_by(sim) %>%
    mutate(cum_confirm = cumsum(new_confirm)) %>%
    ggplot(aes(x = time, y = cum_confirm, group = sim)) +
    geom_line(alpha = 0.1, colour = 'steelblue') +
    geom_point(data = mutate(country_data, sim = 1), size = 2.5, shape = 21, fill = 'white', stroke = 1.5) +
    ggtitle(paste("Total confirmed (active + inactive) cases of COVID-19 in", selected_country)) +
    xlab("Date") +
    ylab("Number of cases")

extract(country_post_fit) %>%
    .$y %>%
    as_tibble() %>%
    add_column(sim = 1:nrow(.), .before = "V1") %>%
    gather(paste0("V", 1:(ncol(.)-1)), key = 'time', value = 'new_confirm') %>%
    mutate(time = as.integer(str_remove(time, "V")) + min(country_data$time) - 1) %>%
    ggplot(aes(x = time, y = new_confirm, group = sim)) +
    geom_line(alpha = 0.1, colour = 'steelblue') +
    geom_point(data = mutate(country_data, sim = 1), size = 2.5, shape = 21, fill = 'white', stroke = 2)

extract(country_post_fit) %>%
    .$mu %>%
    as_tibble() %>%
    add_column(sim = 1:nrow(.), .before = "V1") %>%
    gather(paste0("V", 1:(ncol(.)-1)), key = 'time', value = 'new_confirm') %>%
    mutate(time = as.integer(str_remove(time, "V")) + min(country_data$time) - 1) %>%
    ggplot(aes(x = time, y = new_confirm, group = sim)) +
    geom_line(alpha = 0.1, colour = 'steelblue')

extract(country_post_fit) %>%
    .$sigma_mu %>%
    as_tibble() %>%
    add_column(sim = 1:nrow(.), .before = "V1") %>%
    gather(paste0("V", 1:(ncol(.)-1)), key = 'time', value = 'new_confirm') %>%
    mutate(time = as.integer(str_remove(time, "V")) + min(country_data$time) - 1) %>%
    ggplot(aes(x = time, y = new_confirm, group = sim)) +
    geom_line(alpha = 0.1, colour = 'steelblue')

```

